sudo: false
os:
  - linux
  - osx
language: node_js
node_js:
  - node
  - '8'
  - '7'
  - '6'
  - '5'
  - '4'
  - '0.8'
  - '0.12'
  - '0.10'
before_install:
  - git config --global user.email "jon.schlinkert@sellside.com"
  - git config --global user.name "jonschlinkert"
