sudo: false
os:
  - linux
  - osx
  - windows
language: node_js
node_js:
  - node
  - '11'
  - '10'
  - '9'
  - '8'
before_install:
  - git config --global user.email "jon.schlinkert@sellside.com"
  - git config --global user.name "jonschlinkert"
